apiVersion: v1
kind: Service
metadata:
  name: aceest-fitness-svc
spec:
  type: NodePort
  selector:
    app: aceest-fitness
    track: blue
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30080
